#!/usr/bin/env python3
"""
Auto Content Pipeline - 自動コンテンツ生成パイプライン

HuggingFace Daily Papers → nano-banana-2図解 → X/Discord投稿
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

# Workspace root
WORKSPACE_ROOT = Path(__file__).parent.parent
SKILLS_DIR = WORKSPACE_ROOT / "skills"
DATA_DIR = WORKSPACE_ROOT / "data"

# Import hf_papers module
sys.path.insert(0, str(SKILLS_DIR / "hf-papers" / "scripts"))
import hf_papers


def get_top_paper() -> Optional[dict]:
    """Get top paper from HuggingFace Daily Papers."""
    try:
        papers = hf_papers.fetch_papers(limit=1, use_cache=False)
        if papers:
            return papers[0]
    except Exception as e:
        print(f"Error fetching paper: {e}")
    
    return None


def generate_image_prompt(paper_data: dict) -> str:
    """Generate image prompt from paper data."""
    paper = paper_data.get("paper", paper_data)
    title = paper.get("title", "")
    keywords = paper.get("ai_keywords", [])
    
    prompt = f"""Abstract scientific visualization representing: {title}
Style: Modern, clean, minimalist academic illustration
Colors: Deep blue, purple, cyan gradients with white highlights
Elements: Neural network patterns, data flow, geometric shapes, abstract technology
Keywords: {', '.join(keywords[:5]) if keywords else 'AI, research, innovation'}
The image should be visually striking and suitable for social media sharing."""
    
    return " ".join(prompt.split())


def generate_image(prompt: str, output_dir: Path) -> Optional[str]:
    """Generate image using nano-banana-2 skill."""
    output_dir.mkdir(parents=True, exist_ok=True)
    
    script_path = SKILLS_DIR / "nano-banana-2" / "scripts" / "generate.py"
    
    cmd = [
        sys.executable,
        str(script_path),
        "--prompt", prompt,
        "--aspect-ratio", "16:9",
        "--resolution", "1K",
        "--output-format", "png",
        "--save",
        "--output-dir", str(output_dir)
    ]
    
    print(f"Generating image: {prompt[:100]}...")
    
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=120,
            cwd=WORKSPACE_ROOT
        )
        
        if result.returncode == 0:
            for line in result.stdout.split("\n"):
                if "URL:" in line or "http" in line:
                    for part in line.split():
                        if part.startswith("http"):
                            print(f"Image generated: {part}")
                            return part
        
        if result.stderr:
            print(f"Image generation stderr: {result.stderr}", file=sys.stderr)
            
    except subprocess.TimeoutExpired:
        print("Image generation timed out")
    except Exception as e:
        print(f"Error generating image: {e}")
    
    return None


def generate_explanation(paper_data: dict) -> str:
    """Generate explanation text for the paper."""
    paper = paper_data.get("paper", paper_data)
    title = paper.get("title", "")
    summary = paper.get("ai_summary", paper.get("summary", ""))[:300]
    keywords = paper.get("ai_keywords", [])
    paper_id = paper.get("id", "")
    
    hashtags = " ".join([f"#{kw.replace(' ', '_')}" for kw in keywords[:3]]) if keywords else "#AI #Research"
    
    explanation = f"""📜 {title}

{summary}

🔗 arXiv: {paper_id}
{hashtags} #ONIZUKA_AGI

---
🤖 Generated by ONIZUKA AGI Co.
"""
    
    return explanation


def post_to_x(text: str, image_url: Optional[str] = None) -> bool:
    """Post to X (Twitter) using x-write skill."""
    script_path = SKILLS_DIR / "x-write" / "scripts" / "x_write.py"
    
    cmd = [sys.executable, str(script_path), "tweet", "--text", text]
    
    if image_url:
        cmd.extend(["--media", image_url])
    
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=30,
            cwd=WORKSPACE_ROOT
        )
        
        if result.returncode == 0:
            print("✅ Posted to X")
            return True
        else:
            print(f"❌ Failed to post to X: {result.stderr}")
    except Exception as e:
        print(f"Error posting to X: {e}")
    
    return False


def post_to_discord(text: str, image_url: Optional[str] = None) -> bool:
    """Post to Discord using message tool (placeholder)."""
    # This would use the message tool via subprocess or API
    # For now, just print the content
    print("\n=== Discord Post ===")
    print(text)
    if image_url:
        print(f"Image: {image_url}")
    print("=" * 40)
    return True


def run_pipeline(
    dry_run: bool = False,
    skip_image: bool = False,
    skip_x: bool = False,
    skip_discord: bool = False
) -> dict:
    """Run the full content generation pipeline."""
    
    result = {
        "timestamp": datetime.now().isoformat(),
        "paper": None,
        "image_url": None,
        "explanation": None,
        "x_posted": False,
        "discord_posted": False
    }
    
    # Step 1: Get top paper
    print("📄 Fetching top paper from HuggingFace...")
    paper_data = get_top_paper()
    if not paper_data:
        print("Failed to fetch paper")
        return result
    
    paper = paper_data.get("paper", paper_data)
    result["paper"] = {
        "id": paper.get("id"),
        "title": paper.get("title"),
        "upvotes": paper.get("upvotes", 0)
    }
    print(f"✅ Paper: {paper.get('title')}")
    
    # Step 2: Generate explanation
    print("\n📝 Generating explanation...")
    explanation = generate_explanation(paper_data)
    result["explanation"] = explanation
    print("✅ Explanation generated")
    
    # Step 3: Generate image
    if not skip_image:
        print("\n🎨 Generating visual explanation...")
        prompt = generate_image_prompt(paper_data)
        image_url = generate_image(prompt, DATA_DIR / "generated-images")
        if image_url:
            result["image_url"] = image_url
            print(f"✅ Image: {image_url}")
        else:
            print("⚠️ Image generation failed (continuing without image)")
    
    # Step 4: Post to X
    if not skip_x and not dry_run:
        print("\n🐦 Posting to X...")
        posted = post_to_x(explanation, result.get("image_url"))
        result["x_posted"] = posted
    
    # Step 5: Post to Discord
    if not skip_discord and not dry_run:
        print("\n💬 Posting to Discord...")
        posted = post_to_discord(explanation, result.get("image_url"))
        result["discord_posted"] = posted
    
    return result


def main():
    parser = argparse.ArgumentParser(
        description="Auto Content Pipeline - HuggingFace Papers to X/Discord"
    )
    parser.add_argument("--dry-run", action="store_true",
                       help="Run without posting (just generate content)")
    parser.add_argument("--skip-image", action="store_true",
                       help="Skip image generation")
    parser.add_argument("--skip-x", action="store_true",
                       help="Skip X posting")
    parser.add_argument("--skip-discord", action="store_true",
                       help="Skip Discord posting")
    parser.add_argument("--output", type=str,
                       help="Output JSON file for results")
    
    args = parser.parse_args()
    
    print("=" * 50)
    print("🔄 Auto Content Pipeline")
    print("=" * 50)
    
    result = run_pipeline(
        dry_run=args.dry_run,
        skip_image=args.skip_image,
        skip_x=args.skip_x,
        skip_discord=args.skip_discord
    )
    
    print("\n" + "=" * 50)
    print("📊 Pipeline Result")
    print("=" * 50)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    
    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            json.dump(result, f, indent=2, ensure_ascii=False)
        print(f"\n✅ Results saved to {args.output}")
    
    return 0 if result.get("paper") else 1


if __name__ == "__main__":
    sys.exit(main())
