#!/usr/bin/env python3
"""
週間レポート自動生成スクリプト
毎週日曜21:00に実行し、Discordに通知する
"""

import subprocess
import json
from datetime import datetime, timedelta
from pathlib import Path
import os

# 設定
PROJECT_NUMBER = 1
PROJECT_OWNER = "onizuka-agi-co"
MEMORY_DOCS_PATH = Path("/config/.openclaw/workspace/memory/docs")
DISCORD_WEBHOOK_URL = os.environ.get("WEEKLY_REPORT_WEBHOOK_URL", "")


def get_week_range():
    """今週の日付範囲を取得（月曜〜日曜）"""
    today = datetime.now()
    monday = today - timedelta(days=today.weekday())
    sunday = monday + timedelta(days=6)
    return monday, sunday


def get_completed_tasks_this_week():
    """GitHub Projectから今週完了したタスクを取得"""
    monday, sunday = get_week_range()

    cmd = ["gh", "project", "item-list", str(PROJECT_NUMBER), "--owner", PROJECT_OWNER, "--format", "json"]
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"Error: {result.stderr}")
        return []

    data = json.loads(result.stdout)
    completed_tasks = []

    for item in data.get("items", []):
        if item.get("status") == "Done":
            # タイトルのみ取得（詳細な日付フィルタリングは省略）
            completed_tasks.append(item.get("title", "Unknown"))

    return completed_tasks


def get_memory_docs_this_week():
    """今週の日報から主要な進捗を抽出"""
    monday, sunday = get_week_range()
    docs = []

    # 今週の日報を検索
    current = monday
    while current <= sunday:
        doc_path = MEMORY_DOCS_PATH / current.strftime("%Y/%m/%d") / "index.md"
        if doc_path.exists():
            content = doc_path.read_text()
            # タイトルと最初のセクションを抽出
            lines = content.split("\n")
            title = ""
            summary_lines = []
            in_summary = False

            for line in lines:
                if line.startswith("# "):
                    title = line[2:].strip()
                    in_summary = True
                elif in_summary and line.startswith("## "):
                    if "進捗" in line or "完了" in line or "実施" in line:
                        in_summary = True
                    else:
                        in_summary = False
                elif in_summary and line.strip():
                    summary_lines.append(line)

            if title:
                docs.append({
                    "date": current.strftime("%Y-%m-%d"),
                    "title": title,
                    "summary": "\n".join(summary_lines[:5])  # 最初の5行のみ
                })

        current += timedelta(days=1)

    return docs


def generate_report(completed_tasks, memory_docs):
    """週間レポートを生成"""
    monday, sunday = get_week_range()

    report = f"""# 📊 週間レポート

**期間:** {monday.strftime("%Y-%m-%d")} ~ {sunday.strftime("%Y-%m-%d")}

---

## ✅ 今週の完了タスク ({len(completed_tasks)}件)

"""

    if completed_tasks:
        for task in completed_tasks[:10]:  # 最大10件
            report += f"- {task}\n"
        if len(completed_tasks) > 10:
            report += f"\n...他 {len(completed_tasks) - 10} 件\n"
    else:
        report += "_今週の完了タスクはありません_\n"

    report += "\n---\n\n## 📝 今週の主な進捗\n\n"

    if memory_docs:
        for doc in memory_docs:
            report += f"### {doc['date']}: {doc['title']}\n\n"
            if doc['summary']:
                report += f"{doc['summary']}\n\n"
    else:
        report += "_今週の日報はありません_\n"

    report += """---

_Generated by ONIZUKA AGI Co. Weekly Report Bot_
"""

    return report


def send_to_discord(report):
    """Discord Webhookで通知"""
    if not DISCORD_WEBHOOK_URL:
        print("Warning: DISCORD_WEBHOOK_URL not set")
        return False

    import urllib.request
    import urllib.error

    # Discord用にフォーマット（2000文字制限）
    content = report[:1900] + "..." if len(report) > 1900 else report

    payload = json.dumps({
        "content": content,
        "username": "📊 Weekly Report Bot",
        "allowed_mentions": {"parse": []}
    }).encode('utf-8')

    req = urllib.request.Request(
        DISCORD_WEBHOOK_URL,
        data=payload,
        headers={
            "Content-Type": "application/json",
            "User-Agent": "ONIZUKA-WeeklyReport/1.0"
        }
    )

    try:
        with urllib.request.urlopen(req) as response:
            if response.status == 204:
                print("Report sent to Discord successfully")
                return True
            else:
                print(f"Unexpected response: {response.status}")
                return False
    except urllib.error.HTTPError as e:
        print(f"HTTP Error: {e.code} - {e.reason}")
        return False


def main():
    print("=== Weekly Report Generator ===")
    print(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # データ収集
    print("\n1. Collecting completed tasks...")
    completed_tasks = get_completed_tasks_this_week()
    print(f"   Found {len(completed_tasks)} completed tasks")

    print("\n2. Collecting memory docs...")
    memory_docs = get_memory_docs_this_week()
    print(f"   Found {len(memory_docs)} daily reports")

    # レポート生成
    print("\n3. Generating report...")
    report = generate_report(completed_tasks, memory_docs)
    print(report)

    # Discord送信
    print("\n4. Sending to Discord...")
    if DISCORD_WEBHOOK_URL:
        success = send_to_discord(report)
        if success:
            print("✅ Report sent successfully!")
        else:
            print("❌ Failed to send report")
    else:
        print("⚠️ Discord Webhook URL not configured")


if __name__ == "__main__":
    main()
